### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by sgehrman** [ahammer/FlutterStarfield#1]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  /home/steve/google/FlutterStarfield/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:186: error: resource android:attr/fontVariationSettings not found.
  /home/steve/google/FlutterStarfield/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:187: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
  Command: /home/steve/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-linux.jar/29ef26d8c34d3a404a42504f9d4fd276/aapt2-3.2.1-4818971-linux/aapt2 link -I\
          /home/steve/Android/Sdk/platforms/android-27/android.jar\
          --manifest\
          /home/steve/google/FlutterStarfield/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\
          /home/steve/google/FlutterStarfield/build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\
          @/home/steve/google/FlutterStarfield/build/app/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          /home/steve/google/FlutterStarfield/build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
          --custom-package\
          com.example.fluttermysassa\
          -0\
          apk\
          --output-text-symbols\
          /home/steve/google/FlutterStarfield/build/app/intermediates/symbols/debug/R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-linux Daemon #0
  Output:  /home/steve/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/205d1501b542a00b2fbd9de65f2cb0bb/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

  /home/steve/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/205d1501b542a00b2fbd9de65f2cb0bb/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
  Command: /home/steve/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-linux.jar/29ef26d8c34d3a404a42504f9d4fd276/aapt2-3.2.1-4818971-linux/aapt2 link -I\
          /home/steve/Android/Sdk/platforms/android-27/android.jar\
          --manifest\
          /home/steve/google/FlutterStarfield/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\
          /home/steve/google/FlutterStarfield/build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\
          @/home/steve/google/FlutterStarfield/build/app/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          /home/steve/google/FlutterStarfield/build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
          --custom-package\
          com.example.fluttermysassa\
          -0\
          apk\
          --output-text-symbols\
          /home/steve/google/FlutterStarfield/build/app/intermediates/symbols/debug/R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-linux Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by ahammer** [comment]
I've removed android/ios folders (as they are on a old flutter SDK and hence why this didn't build)

There is new building instructions provided.

Additionally, a link to my flutter clock, which also has a revised starfield amongst other things that make it a much better learning example.
